### ISSUE TITLE
[Mod Suggestion] Applied Energistics 2

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica8#10]
### URL

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2

### Why would you like the mod added?

Maybe Refined Storage is easier way to make a storage system and more additional mods of it than Applied Energistics 2.
But I really want it back to the modpack. I think it is more challenging and logical than RS :3

**Comment by tuca1234567890** [comment]
I second this. The new AE2 versions resolved issues from previous versions like lag and finally implemented fluid autocrafting and a wireless crafting terminal. The latest Forge version in CF is still an Alpha from 5 hours ago though, I don't know if it's stable enough yet.

**Comment by YashTFEM** [comment]
RS is much simpler much cleaner, and much easier to setup what without the channels and whatnot. I'm pretty sure we'd all like it so both storage systems are there to give us two nice options as to what wed prefer. Devs please considering adding both(RS when it's released) to the pack since I'm sure 50% likes AE2, 50% likes RS

**Comment by YashTFEM** [comment]
Tinkers is very very different from Tetra.

**Comment by YashTFEM** [comment]
RS is not that different from AE2 in that its a digital storage mod.

**Comment by theboo** [comment]
Oh look, Enigmatica 8's first ae2 vs RS debate! 

Cute!

**Comment by YashTFEM** [comment]
Also, tinkers and tetra are the only 2 tools mods in the pack. The devs want to give us a choice as to what to use for tools. For storgae we have many things like occultism, botania corporea, pretty, pipes, and then RS. When we had these many storage options the devs didn't see the point of adding more.

**Comment by TemperedFool** [comment]
RS and AE2 are both relatively heavy mods that do the same thing; it's not that we CAN'T include both, but there is basically space for so many major content mods in a pack before it collapses around its ankles. We went with RS for E6 because we decided it was better for E6; I imagine whichever one is better for E8 will get selected for E8 long run.

Also to consider - Expert Mode. It's relatively easy to take soem mods and slot them into a hierarchy by changing some of the capabilities of various items and machines. RS and AE2 are redundant - there's not really a way to differentiate them, so it really just ends up being twice the work to integrate both of them.

There is a lot of storm and thunder about how much this choice matters in the discord - people are very opinionated. In practice I don't actually think the choice matters that much, as long as the one we choose is good.

**Comment by NillerMedDild** [comment]
I'll have a look in-game, but I cannot promise AE2 will remain in the pack should we decide to add it :)

**Comment by Technici4n** [comment]
If you encounter any issue, please let us know. :)

**Comment by NillerMedDild** [comment]
Will do, thanks!
